@startuml
salt
{
  001 | <b>User signpost - <username>
  002 | {You have <b>$1,234.45 | in your wallet.}
  003/004 | {[Bank web] | create bank account here}
  005/006 | {[Visit ATM] | perform actions with your card}

  .|--

  007 | <b>Your bank accounts:
  008 | {
          {+
            <b>Account_2
            Personal account
            ==
            {<b>card: | 123456789/1234}
            {<b>expiration: | dd.mm.yyyy}
          } | {  . } |
          {+
            <b>Account_2
            Personal account
            ==
            {<b>You don't have
            <b>receive your card yet...}
          }
        }
  . | .
  009 | {+<b> You have no bank account}
}

@enduml